source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/shookHead/LHPodSpec.git'

use_frameworks!

platform :ios, '9.0'

target 'LHTools_Example' do
  pod 'LHTools', :path => '../'

  target 'LHTools_Tests' do
    inherit! :search_paths

    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'HandyJSON'
    pod 'MJRefresh'
    pod 'SwiftyUserDefaults'
    pod 'IQKeyboardManagerSwift'
    pod 'SQLite.swift'
    pod 'Hero'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxDataSources', '~> 3.0'
    
    pod 'NVActivityIndicatorView'
    pod 'CLImagePickerTool'
    pod 'JXPhotoBrowser'
    pod 'Charts'
    pod 'JXSegmentedView'
    pod 'JXPagingView/Paging'
    pod 'AttributedString'
    pod 'LTMorphingLabel'
    pod 'CollectionKit'
    pod 'SnapKit'
  end
end
