source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/shookHead/LHPodSpec.git'

use_frameworks!

platform :ios, '12.0'
#inhibit_all_warnings!

target 'LHTools_Example' do
  pod 'LHTools', :path => '../'

  target 'LHTools_Tests' do
    inherit! :search_paths
#    pod 'HandyJSON', :git => 'https://github.com/Miles-Matheson/HandyJSON.git', :branch => 'master'
#    pod 'Alamofire'
#    pod 'Kingfisher'
#    pod 'MJRefresh'
#    pod 'MBProgressHUD'
#    pod 'SwiftyUserDefaults'
#    pod 'IQKeyboardManagerSwift'
#    pod 'SQLite.swift'
#    pod 'Hero'
#
#    pod 'NVActivityIndicatorView'
#    pod 'ZLPhotoBrowser'
#    pod 'JXPhotoBrowser'
#    pod 'SnapKit'

    
#    pod 'Charts'
#    pod 'JXSegmentedView'
#    pod 'JXPagingView/Paging'
#    pod 'AttributedString'
#    pod 'LTMorphingLabel'
#    pod 'CollectionKit'
#    pod 'RxSwift',    '~> 4.0'
#    pod 'RxCocoa',    '~> 4.0'
#    pod 'RxDataSources', '~> 3.0'
  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      if !deployment_target.nil? && !deployment_target.empty? && deployment_target.to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
