source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/shookHead/LHPodSpec.git'

use_frameworks!

platform :ios, '10.0'
#inhibit_all_warnings!

target 'LHTools_Example' do
  pod 'LHTools', :path => '../'

  target 'LHTools_Tests' do
    inherit! :search_paths
    
#    pod 'Alamofire'
#    pod 'Kingfisher'
#    pod 'HandyJSON'
#    pod 'MJRefresh'
#    pod 'MBProgressHUD'
#    pod 'SwiftyUserDefaults'
#    pod 'IQKeyboardManagerSwift'
#    pod 'SQLite.swift'
#    pod 'Hero'
#
#    pod 'NVActivityIndicatorView'
#    pod 'ZLPhotoBrowser'
#    pod 'JXPhotoBrowser'
#    pod 'SnapKit'

    
#    pod 'Charts'
#    pod 'JXSegmentedView'
#    pod 'JXPagingView/Paging'
#    pod 'AttributedString'
#    pod 'LTMorphingLabel'
#    pod 'CollectionKit'
#    pod 'RxSwift',    '~> 4.0'
#    pod 'RxCocoa',    '~> 4.0'
#    pod 'RxDataSources', '~> 3.0'
  end
end
#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#        end
#    end
#end


pre_install do |installer|
    remove_swiftui()
end

def remove_swiftui
  # 解决 xcode13 Release模式下SwiftUI报错问题
  system("rm -rf ./Pods/Kingfisher/Sources/SwiftUI")
  code_file = "./Pods/Kingfisher/Sources/General/KFOptionsSetter.swift"
  code_text = File.read(code_file)
  code_text.gsub!(/#if canImport\(SwiftUI\) \&\& canImport\(Combine\)(.|\n)+#endif/,'')
  system("rm -rf " + code_file)
  aFile = File.new(code_file, 'w+')
  aFile.syswrite(code_text)
  aFile.close()
end
