//
//  LHInternationalization.swift
//  LHTools
//
//  Created by 海 on 2023/4/24.
//  Copyright © 2023 CocoaPods. All rights reserved.
//

public var lhCancle = "取消"
public var lhLoading = "加载中.."
public var lhClickRefresh = "点击刷新"
public var lhSuccessfullySaved = "保存成功"
public var lhYear = "年"
public var lhMonth = "月"
public var lhDay = "日"
public var lhDivide = "分"
public var lhSecond = "秒"
public var lhMonday = "周一"
public var lhTuesday = "周二"
public var lhWednesday = "周三"
public var lhThursday = "周四"
public var lhFriday = "周五"
public var lhSaturday = "周六"
public var lhSunday = "周日"
public var lhDrop = "点"
public var lhDateError = "日期区间选择错误"
public var lhEndDate = "结束日期"
public var lhUpdateNow = "马上更新"

public var lhDataParsingFailed = "数据解析失败"
public var lhRequestCancelled = "请求被取消"
public var lhInvalidRequestAddress = "请求地址无效"
public var lhUnableAccessNetwork = "无法访问网络"
public var lhNetworkException = "网络异常，请求失败"
public var lhFlashCannotTurned = "闪光灯无法打开"
public var lhRequestTimeout = "请求超时"
public var lhPermanent = "永 久"
public var lhPhotoGraph = "拍照"
public var lhUsingTest = "使用测试服"
public var lhPermissionCamera = "您还没有打开相机权限"
public var lhAccessLocation = "访问定位"
public var lhAccessRecording = "录音权限"
public var lhPermissionRecording = "您还没有打开录音权限"
public var lhPleaseSelect = "请选择"
public var lhPermissionAlbum = "您还没有打开相册权限"
public var lhDiscoveringNewVersion = "发现新版本"
public var lhNoData = "暂无数据"
public var lhRemindLater = "稍后提醒"
public var lhGoOpen = "去打开"
public var lhPermissionLocation = "您还没有打开定位权限"
public var lhUploadFailed = "上传失败"
public var lhServerUnreachable = "服务器无法访问"
public var lhLoginFailed = "登录失效，请重新登录"
public var lhAccessingCameras = "访问相机"
public var lhSelectFromAlbum = "从相册选取"
public var lhGood = "好"

public var lhFailedSaveImageAlbum = "保存图片到相册失败"
public var lhAccessingAlbum = "访问相册"
public var lhSelectDateTime = "选择日期和时间"
public var lhUnableScanCode = "扫描不到二维码"
public var lhDetermine = "确定"
public var lhDetermineSpace = "确 定"
public var lhTimeSelectionError = "时间选择错误"
public var lhPictures = "上传图片"

public var lhConfirm = "确认"
public var lhStartDate = "开始日期"
public var lhDeviceCannotFlash = "当前设备识别不到闪光灯"
public var lhCodeRecognitionError = "二维码识别异常，请重新扫描"
public var lhNotLogged = "未登录，请登录"
public var lhRequestFailure = "请求失败"

public var lhInvalidUrl = "无效的url"
public var lhUnknownError = "未知错误"
public var lhSaveToAlbum = "视频已保存到相册"
public var lhMoveVideoFail = "移动视频文件失败"

