//
//  LHInternationalization.swift
//  LHTools
//
//  Created by 海 on 2023/4/24.
//  Copyright © 2023 CocoaPods. All rights reserved.
//

var lhCancle = "取消"
var lhLoading = "加载中.."
var lhClickRefresh = "点击刷新"
var lhSuccessfullySaved = "保存成功"
var lhYear = "年"
var lhMonth = "月"
var lhDay = "日"
var lhDivide = "分"
var lhSecond = "秒"
var lhMonday = "周一"
var lhTuesday = "周二"
var lhWednesday = "周三"
var lhThursday = "周四"
var lhFriday = "周五"
var lhSaturday = "周六"
var lhSunday = "周日"
var lhDrop = "点"
var lhDateError = "日期区间选择错误"
var lhEndDate = "结束日期"
var lhUpdateNow = "马上更新"

var lhDataParsingFailed = "数据解析失败"
var lhRequestCancelled = "请求被取消"
var lhInvalidRequestAddress = "请求地址无效"
var lhUnableAccessNetwork = "无法访问网络"
var lhNetworkException = "网络异常，请求失败"
var lhFlashCannotTurned = "闪光灯无法打开"
var lhRequestTimeout = "请求超时"
var lhPermanent = "永 久"
var lhPhotoGraph = "拍照"
var lhUsingTest = "使用测试服"
var lhPermissionCamera = "您还没有打开相机权限"
var lhAccessLocation = "访问定位"
var lhPleaseSelect = "请选择"
var lhPermissionAlbum = "您还没有打开相册权限"
var lhDiscoveringNewVersion = "发现新版本"
var lhNoData = "暂无数据"
var lhRemindLater = "稍后提醒"
var lhGoOpen = "去打开"
var lhPermissionLocation = "您还没有打开定位权限"
var lhUploadFailed = "上传失败"
var lhServerUnreachable = "服务器无法访问"
var lhLoginFailed = "登录失效，请重新登录"
var lhAccessingCameras = "访问相机"
var lhSelectFromAlbum = "从相册选取"
var lhGood = "好"

var lhFailedSaveImageAlbum = "保存图片到相册失败"
var lhAccessingAlbum = "访问相册"
var lhSelectDateTime = "选择日期和时间"
var lhUnableScanCode = "扫描不到二维码"
var lhDetermine = "确定"
var lhDetermineSpace = "确 定"
var lhTimeSelectionError = "时间选择错误"
var lhPictures = "上传图片"

var lhConfirm = "确认"
var lhStartDate = "开始日期"
var lhDeviceCannotFlash = "当前设备识别不到闪光灯"
var lhCodeRecognitionError = "二维码识别异常，请重新扫描"
var lhNotLogged = "未登录，请登录"
var lhRequestFailure = "请求失败"
